### PR TITLE
WIP - Upgrade Ansible to 2.1.3

### PR DESCRIPTION
**Pull request by tersmitten**
This version seems to work without any adjustment to the roles.

We can [upgrade to 2.2.*](https://github.com/kvz/frey/pull/49) from here, but I'll make the role changes first.

### CODE REVIEW

**Comment by kvz** [comment]
Great!

**Comment by tersmitten** [comment]
I use `WIP` to indicate "work in progress", but if you're confident that everything work I'm too :-)

**Comment by kvz** [comment]
Woops missed teh WIP :) Let me get the tests back on their feet :)

**Comment by tersmitten** [comment]
I'll double check it this week, but an initial run in tusd seemed to work

**Comment by tersmitten** [comment]
Done you have any recommendations on testing the roles that are not used in tusd?

**Comment by kvz** [comment]
> Do you have any recommendations on testing the roles that are not used in tusd?

There is a `test/scenario/install/` that does some basic testing, to see if roles work at all. The problem with this is it targets localhost, so could be e.g. OSX for instance, and we obviously don't want to install e.g. rsyslog on that. 

On travis, the localhost thing would be no problem though.

I wonder if we should make docker/vagrant mandatory for development, so that we can test roles in that, and target localhost on Travis.. thoughts?

**Comment by tersmitten** [comment]
For all the roles I create there're both automated [travis-ci tests](https://github.com/Oefenweb/ansible-rsyslog/blob/master/.travis.yml) on all supported Ansible versions and a [Vagrantfile](https://github.com/Oefenweb/ansible-rsyslog/blob/master/Vagrantfile) with all supported operating systems. This makes accurate testing much easier.

How do you feel about swapping some roles (by better ones) and / or improving ones that you already use? 

Also what is the OS of your servers, always Ubuntu 16.04?

**Comment by kvz** [comment]
Your ansible upgrade fixed the uppy-server auto-deploy ❤️ 😄  https://travis-ci.org/transloadit/uppy-server/builds/174487054

**Comment by kvz** [comment]
> For all the roles I create there're both automated travis-ci tests on all supported Ansible versions and a Vagrantfile with all supported operating systems. This makes accurate testing much easier.
> How do you feel about swapping some roles (by better ones) and / or improving ones that you already use?

That all sounds great! I wonder if Vagrant would get slow though since we'd want to reset to a clean state every test(?)

> Also what is the OS of your servers, always Ubuntu 16.04?

NixOS (forget that :), trusty. Travis uses precise by default, and we use Travis for many things. We have plans to upgrade to xenial at some point (probably a year or so away still tho).

**Comment by tersmitten** [comment]
> Travis uses precise by default

This works great for us: https://github.com/Oefenweb/ansible-rsyslog/blob/master/.travis.yml#L3

We only use the Vagrant file for manual testing, or upgrades to 16.04 :-), or testing on operating systems that I do not have on my servers, but are supported (e.g. `Debian`)

**Comment by kvz** [comment]
Very cool!

**Comment by kvz** [comment]
The way the acceptance tests work currently though is that you run them locally, and all output is saved as fixtures (some things like time & IP are stripped) and committed if looking good. Next runs are compared to the fixtures.

So we'd likely use the local thing also in an automated way, hence docker might be a lot faster for our purposes. I think when using travis trusty and sudo:false, we can use docker both locally & on travis... ?

**Comment by tersmitten** [comment]
> I think when using travis trusty and sudo:false, we can use docker both locally & on travis

Yes

This is how [geerlingguy](https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml) runs all his Ansible role tests in Docker

**Comment by kvz** [comment]
I think our future selves will be pleased with us once we can have microsecond-ranged retries/resets for tests, vs having to throw away and boot VMs to get clean slates. If you agree, I'd like to try the docker approach for this

**Comment by tersmitten** [comment]
Sure, but roles might need to work differently in docker than on bare metal / vm's. Let's provide both a `Dockerfile` and a `Vagrantfile`. This way we're flexible to switch (Docker being the default solution)

**Comment by kvz** [comment]
Lovvit 👌

**Pull request merged**
