### PR TITLE
Replacing terminal images with HTML, adding /docs/ permalink 

### PR DESCRIPTION
**Pull request by roo-shy**
screen shot 2016-09-26 at 11 06 15 pm

### CODE REVIEW

**Comment by kvz** [comment]
Thanks Rooshy, looking good! Just:

**Comment by roo-shy** [comment]
👌

**Comment by roo-shy** [comment]
I aligned the commands content, although it is still off on less than 400px view. Not sure what would be the solution but I think giving commands color or weight will help. I also could look into responsive tables to resolve this view: 

screen shot 2016-09-27 at 1 33 45 pm

**Comment by kvz** [comment]
That look very acceptable to me for such a small view - let's merge this puppy! 🐶

**Pull request merged**
